### ISSUE TITLE
Core200S Has Multiple Device Models

### ISSUE THREAD

**Issue by FidgetyRat** [webdjoe/pyvesync#101]
I was working with someone on the HomeAssistant side to diagnose an issue of Core200S devices not being recognized by the integration.

https://github.com/home-assistant/core/issues/61417

I discovered that Levoit produces more than one version of the Core 200s device and sells them in the same packaging. A sticker on the back of the device lists the model number as "LAP-C201S-AUSR". Both models are identical as far as I can tell with the exception of firmware numbers and the deviceType returned by the API.

In the thread above, I made some quick and dirty changes to pyvesync and the HA integration to recognize this model as a Core200S and HA then uses it no problem identical to its brother.

It may be worth while to add support for multiple device types for each device and translate to one known variant. For example, when the API returns the LAP-C201S-AUSR device, simply swap it's String for Core200S and thus the remainder of the library (and the HA integration) will simply treat the device as a Core200S as it should be.

**Comment by webdjoe** [comment]
I've added the device type. Please test to make sure that it works properly before I publish #104

**Comment by pedroche90** [comment]
I have an issue too. i  have a levoit dual 200S humidifier and not recognized on pyvesync.


        from pyvesync import VeSync

        manager = VeSync("*@gmail.com", "", “Europe/Madrid”)
        manager.login()
        True

        manager.update()
        my_switch = manager.outlets[0]
        Traceback (most recent call last):
        File “”, line 1, in
        IndexError: list index out of range



My model is LUH-D301S-WEU

**Comment by webdjoe** [comment]
@pedroche90 this should be fixed in the current release
