### ISSUE TITLE
Support for Classic 200S Humidifier?

### ISSUE THREAD

**Issue by NickM-27** [webdjoe/pyvesync#102]
Hi, I just got my Classic 200S Humidifier and it does not appear with the API, but it does show in the Vesync app across my devices.

**Comment by webdjoe** [comment]
Any log messages?

**Comment by NickM-27** [comment]
@webdjoe Working on it but the app method is giving me no luck. Am I able to get enough information from just running this with python locally with my account details?

**Comment by NickM-27** [comment]
I know it is called the `Classic200S` and it is the same as the `Classic300S` except it does not have a night light.

**Comment by NickM-27** [comment]
I'm happy to make a PR for this tomorrow after I have some time to test

**Comment by webdjoe** [comment]
Merged
