### ISSUE TITLE
Specifying a Date Range to get_monthly_energy()

### ISSUE THREAD

**Issue by sojimp** [webdjoe/pyvesync#111]
In the VeSync app, it displays a rolling 30 days, but the API endpoint /*/v1/device/energymonth returns the days of the current month only. For example, as of today February 5th I get five days in `energy['month']['data']`. I have been studying the code of `pyvesync` but I cannot see any way to specify a range like the app does.

I thought maybe the app is polling regularly and building its own database, but then I realized a date like April 30, 2022 would require polling seconds before midnight to not lose data. And in the app it doesn't look like the last day of any month is lower than the rest.

Does the API support a date range? I can improve the code, but I don't know what to pass to the API.

**Comment by webdjoe** [comment]
It lets you go back a full year with `outlet.get_yearly_energy()` and get the `energy['year']` value but there's no way that I am aware of to specify two dates.
