### ISSUE TITLE
Levoit Plasma Pro 400S

### ISSUE THREAD

**Issue by loumarjr** [webdjoe/pyvesync#115]
Hello,

After hours of trying to get this to work, I finally have the vesync_formatbce integration in my list. However, the integration is not finding my two devices, or any entities listed under the integration (neither did the built in vesync integration find any).

The only issue I can think of that may be causing the problem is that I have a Plasma Pro 400s, which is identical to the Core 400s, except that the Plasma Pro has an ionization feature. The manufacturer (Levoit) was contacted and stated this fact.

Is it possible that the name of the Plasma Pro is different from the Core when it reports the name to the API and is preventing the integration from finding the devices? I have two Plasma Pro’s on my account, and neither is showing in the integration.

If this is the case, can the name of the Plasma Pro be added to the integration? I’m not even sure how to find the name that is reported to the API.

Issue: Levoit Plasma Pro 400S

Thank you for all your help!!

**Comment by webdjoe** [comment]
This probably has another device type. If you instantiate the manager you should see the device type that isn't found in the log. We could try using same api as 400S, just adding that device type to the list.

**Comment by loumarjr** [comment]
Thank you for your reply.  Can you describe exactly what I need to do to get this information?  Im not sure how to extract the infomation from the manager.  I dont know how to open the manager.  Im hopeful it is the same api because the company stated it is very similar to the Core 400S.  All my other devices on your integration work perfectly (Wifi plugs).   Thank you!!

**Comment by loumarjr** [comment]
As a guess, since the device type of the Core 400s is "Core400S": "fan",  could the Plasma Pro 400S be "PlasmaPro400S": "fan",  ?

Could you integerate that in your program?  Not sure how to confirm the correct name of the device.



Thanks!!

**Comment by loumarjr** [comment]
Just wondering if you had time to integrete the Plasma Pro 400s?  I really am not sure how to access the manager to see the device type.  Thank you for your time.

**Comment by webdjoe** [comment]
I was able to find the device type, will have a branch for you to test
later today

**Comment by loumarjr** [comment]
Thank you!!

**Comment by loumarjr** [comment]
I'm not sure where to find the branch.  Could you provide a web link?  Thanks for all your hard work!!

**Comment by webdjoe** [comment]
Added plasma models - please test to make sure it works correctly - https://github.com/webdjoe/pyvesync/tree/air-refactor

**Comment by loumarjr** [comment]
Thank you for updating.  I am kind of new at this.  Do I overwrite the old code in my "/config/custom_components/vesync_formatbce" folder with the new code that you provided in the above link?

**Comment by webdjoe** [comment]
I completely forgot how HA's custom components work.  Your best bet would be to just clone that branch and write a simple test script by following the readme
