### ISSUE TITLE
Feature Night Light typo in dict?

### ISSUE THREAD

**Issue by borpin** [webdjoe/pyvesync#125]
https://github.com/webdjoe/pyvesync/blob/c41eb8a77e68cc357f558e4fa413e42f9ba68658/src/pyvesync/vesyncfan.py#L21

I note that this is spelt `night_light` in the other 2 devices but `nightlight` here. Is that a typo?

or is the error the other way round

https://github.com/webdjoe/pyvesync/blob/c41eb8a77e68cc357f558e4fa413e42f9ba68658/src/pyvesync/vesyncfan.py#L843

**Comment by webdjoe** [comment]
Thanks for the catch!

**Comment by jspayd** [comment]
Can confirm that that the nightlight is indeed broken on the Classic300S in the latest release. In addition, the Classic200S is marked as having a nightlight even though it doesn't. I can create a separate issue for that if necessary.

**Comment by webdjoe** [comment]
Fixed in #129 publishing to pypi
