### ISSUE TITLE
Dual200S modes and mist level

### ISSUE THREAD

**Issue by borpin** [webdjoe/pyvesync#126]
https://github.com/webdjoe/pyvesync/blob/c41eb8a77e68cc357f558e4fa413e42f9ba68658/src/pyvesync/vesyncfan.py#L25-L34

My Dual200S only has 2 modes `auto` & `manual`. Setting `sleep` has no effect.

It also only has 2 Mist levels - Low (1) and High (2). If these are set, the unit automatically switches to manual mode.

**Comment by webdjoe** [comment]
I took out sleep mode

`list(range(1,3))` = `[1,2]` Does this not work properly when you set the mist level?

**Comment by borpin** [comment]
> `list(range(1,3))` = `[1,2]` Does this not work properly when you set the mist level?

Ah, I misinterpreted that. I think now the version of the HA integration I'm using is picking up the config from your library, it is OK.

Cheers

**Comment by webdjoe** [comment]
Fixed in #129 publishing package
