### ISSUE TITLE
Air quality has different attribute key on LAP-C401S-WAAA

### ISSUE THREAD

**Issue by auliarshad** [webdjoe/pyvesync#133]
Hi @webdjoe I found out that my LAP-C401S-WAAA has different key to identify real time air quality value.

https://github.com/webdjoe/pyvesync/blob/12736dd9868f6f45bfdf5ea01d4f1e142066943b/src/pyvesync/vesyncfan.py#L196

When I tried to debug the device dictionary, it giving output:
```
{
  'enabled': True,
  'filter_life': 100,
  'mode': 'manual',
  'level': 1,
  'air_quality': 1,
  'air_quality_value': 9,
  'display': True,
  'child_lock': False,
  'configuration': {
    'display': True,
    'display_forever': True,
    'auto_preference': {
      'type': 'default',
      'room_size': 0
    }
  },
  'extension': {
    'schedule_count': 1,
    'timer_remain': 0
  },
  'device_error_code': 0
}
```
Somehow `air_quality` will always return 1, while `air_quality_value` giving real time data.

**Comment by alexanv1** [comment]
This regressed as part of commit https://github.com/webdjoe/pyvesync/commit/1aae09bc4b5ab6ba69bcf1fd96fe58f5bed2deec
The library used to consume ```air_quality_value``` but after the above commit it's now consuming ```air_quality``` which looks like some sort of an enum (bad, ok, good or something like that).

I already asked @webdjoe in PR https://github.com/webdjoe/pyvesync/pull/135 whether it's possible to go back to previous behavior.

**Comment by webdjoe** [comment]
Release published. I left both `air_quality` and `air_quality_value` to ensure compatibility. Let me know if there still are any issues
