### ISSUE TITLE
Can't import python package on my mac Monterey.

### ISSUE THREAD

**Issue by aphixe** [webdjoe/pyvesync#136]
after i use pip install, i get Successfully installed pyvesync-2.0.2
=============
python3
Python 3.8.9 (default, Mar 30 2022, 13:51:17) 
[Clang 13.1.6 (clang-1316.0.21.2.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyvesync import VeSync
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pyvesync'
=============
python2
Python 2.7.18 (v2.7.18:8d21aa21f2, Apr 19 2020, 20:48:48) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyvesync import VeSync
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyvesync/__init__.py", line 1, in <module>
    from .vesync import VeSync
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyvesync/vesync.py", line 72
    def energy_update_interval(self) -> int:
                                     ^
SyntaxError: invalid syntax

So i don't know why this is going on

**Comment by webdjoe** [comment]
pyvesync supports python 3.6+ only - I'm not sure how python on MacOS works but it looks like you have python 3.8 installed but it is running your script through a python 2.7 environment

**Comment by aphixe** [comment]
updated to latest python 3 using installer for mac. and ran my code and good news it worked. turn on a light.

**Comment by webdjoe** [comment]
Great, glad to hear it!
