### ISSUE TITLE
Release / Update PyPi

### ISSUE THREAD

**Issue by sdrapha** [webdjoe/pyvesync#139]
Hi, just wondering if you can create a tag/release and update the PyPi version?
On my last PR I already bumped the version. But without releasing it, HomeAssistant can't pick up the latest code.
I already have the home assistant component code done for the valceno multicolor bulb, but I was waiting for the PyPi update to push to the PR. so the CI doesn't fail because mismatching dependencies.

**Comment by webdjoe** [comment]
Sorry for the wait, just updated

**Comment by sdrapha** [comment]
thanks!!😀
