### ISSUE TITLE
Hey guys! Do you have Vesync api development document?

### ISSUE THREAD

**Issue by chenbaoding2818** [webdjoe/pyvesync#141]

**Comment by webdjoe** [comment]
No, just have to capture packets with Charles proxy on the iPhone app. The Android app uses SSL pinning to prevent packet captures

**Comment by HamzaETTH** [comment]
It's possible to do with a rooted android device and proxydroid + this xposed module [https://github.com/ViRb3/TrustMeAlready](https://github.com/ViRb3/TrustMeAlready) that disable ssl verification and pinning
