### ISSUE TITLE
OasisMist: LUS-04515-WUS is listed but Amazon has it as LUH-O451S-WUS instead 

### ISSUE THREAD

**Issue by JamesValero** [webdjoe/pyvesync#157]
Is the currently supported model (README) name a typo as I cannot find LUS-04515-WUS on google. Amazon has the model as LUH-O451S-WUS instead. Notice the O is the letter O. 

https://a.co/d/2lE4h49 (non-affiliated link)

thanks!

**Comment by webdjoe** [comment]
Fixed in the latest release. The typo was only in the readme so the device should still work
