### ISSUE TITLE
Broken pyvesync 2.1.0

### ISSUE THREAD

**Issue by gmariotti** [webdjoe/pyvesync#163]
Based on https://github.com/home-assistant/core/pull/82199#issuecomment-1332760632, it seems that the latest release of pyvesync is an empty one, only containing the metadata of the package. Would it be possible to fix it?

**Comment by webdjoe** [comment]
Uploading package now, can't replace so it will be 2.1.1. I have no idea how that happened

**Comment by gmariotti** [comment]
Thank you @webdjoe 🙇

**Comment by gmariotti** [comment]
sorry to ping you again on this issue, could you update the `setup.py` with the new version and tag the commit for 2.1.1. Seems that this is a requirement for home-assistant (see [comment](https://github.com/home-assistant/core/pull/83146#discussion_r1038758057))
