### ISSUE TITLE
Add timer for Purifier Core300S

### ISSUE THREAD

**Issue by Flobul** [webdjoe/pyvesync#165]
Hi.

I just found a method not implemented yet. (getTimer)

POST https://smartapi.vesync.com/cloud/v2/deviceManaged/bypassV2

`{
  "appVersion": "1.1",
  "phoneBrand": "Jeedom-VeSync",
  "phoneOS": "Jeedom-VeSync",
  "traceId": 1670004564681,
  "acceptLanguage": "fr",
  "region": "EU",
  "timeZone": "Europe\/Brussels",
  "accountID": "1234567",
  "token": "ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWX==",
  "method": "bypassV2",
  "debugMode": true,
  "deviceRegion": "EU",
  "cid": "ABCDEFGHIJKLMNOPQRSTUVWXYZ123456",
  "configModule": "WiFiBTOnboardingNotify_AirPurifier_Core300S_EU",
  "payload": {
    "data": {},
    "method": "getTimer",
    "source": "APP"
  }
}`

Response, when I launch a timer of 30 minutes :
`{
    "traceId": "1670004564681",
    "code": 0,
    "msg": "request success",
    "module": null,
    "stacktrace": null,
    "result": {
        "traceId": "1670004564681",
        "code": 0,
        "result": {
            "timers": [
                {
                    "id": 1,
                    "remain": 1796,
                    "total": 1800,
                    "action": "off"
                }
            ]
        }
    }
}`

When there is no timer :
`{
	"traceId": "1670004564681",
	"code": 0,
	"msg": "request success",
	"module": null,
	"stacktrace": null,
	"result": {
		"traceId": "1670004564681",
		"code": 0,
		"result": {
			"timers": []
		}
	}
}`

On the App

![Screenshot_20221203-094036_VeSync](https://user-images.githubusercontent.com/46993341/205432748-c9d2b8db-f1b8-485a-81fa-fce7e8293de6.jpg)

![Screenshot_20221203-094048_VeSync](https://user-images.githubusercontent.com/46993341/205432747-3a4a32c6-6787-4c67-9d7c-35026d1f1b6f.jpg)

Can't manage to get action command to start/stop timer or the Schedule method.
I tried Charles and successfully created a proxy between my phone (android and iPad) and my Mac, but nothing in the catch except this:
<img width="1425" alt="Capture d’écran 2022-12-03 à 10 17 07" src="https://user-images.githubusercontent.com/46993341/205433693-19ab7c67-7363-442f-a2b3-e3afe21a78bf.png">
Every CONNECT are failed and on the app, it doesn't load data and I got an error.
How do you manage to catch requests?

**Comment by webdjoe** [comment]
I believe the timer is done in app. I haven't found any calls for it either. Reopen if you have any updates

**Comment by Flobul** [comment]
Found it :

Add and delete methods are addTimer and delTimer.

{"appVersion":"1.1","phoneBrand":"Jeedom-VeSync","phoneOS":"Jeedom-VeSync","traceId":1670613945984,"acceptLanguage":"fr","region":"EU","timeZone":"Europe\/Brussels","accountID":"1234567","token":"ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWX==","method":"bypassV2","debugMode":true,"deviceRegion":"EU","cid":"ABCDEFGHIJKLMNOPQRSTUVWXYZ123456","configModule":"WiFiBTOnboardingNotify_AirPurifier_Core300S_EU","payload":{"data":{"total":1900,"action":"off"}, "method":"addTimer","source":"APP"}}

`{
    "traceId": "1670613945984",
    "code": 0,
    "msg": "request success",
    "module": null,
    "stacktrace": null,
    "result": {
        "traceId": "1670613945984",
        "code": 0,
        "result": {
            "id": 1
        }
    }
}`

On the app, the timer is set to 1900 seconds.

If the purifier status is disable, error "code": 11005000.
If there is already a timer set, and you launch it with this method above, it overwrites it.

**Comment by Flobul** [comment]
To erase it:

{"appVersion":"1.1","phoneBrand":"Jeedom-VeSync","phoneOS":"Jeedom-VeSync","traceId":1670613945984,"acceptLanguage":"fr","region":"EU","timeZone":"Europe\/Brussels","accountID":"1234567","token":"ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWX ==","method":"bypassV2","debugMode":true,"deviceRegion":"EU","cid":"ABCDEFGHIJKLMNOPQRSTUVWXYZ123456","configModule":"WiFiBTOnboardingNotify_AirPurifier_Core300S_EU","payload":{"data":{"id":1}, "method":"delTimer","source":"APP"}}

`{
    "traceId": "1670613945984",
    "code": 0,
    "msg": "request success",
    "module": null,
    "stacktrace": null,
    "result": {
        "traceId": "1670613945984",
        "code": 0
    }
}`

if you put the wrong id (ie: id 0), error "code": 11000000.

Either way, only id number 1 seems to be possible. In my tests, I didn't see any other number.

**Comment by webdjoe** [comment]
Test out new branch - #183

**Comment by webdjoe** [comment]
Added to release [2.1.7](https://github.com/webdjoe/pyvesync/releases/tag/2.1.7)
