### ISSUE TITLE
Add device COSORI model CS158-AF

### ISSUE THREAD

**Issue by lovicub** [webdjoe/pyvesync#168]
Please add Air Fryer, would like to set up HA integration
 
{'traceId': '1670631748', 'code': 0, 'msg': 'request success', 'module': None, 'stacktrace': None, 'result': {'total': 1, 'pageSize': 100, 'pageNo': 1, 'list': [{'deviceRegion': 'EU', 'isOwner': True, 'authKey': None, 'deviceName': 'COSORI', 'deviceImg': 'https://image.vesync.com/defaultImages/deviceDefaultImages/wifi_airfryer_cs158-af_eu_240.png', 'cid': '----------------------------', 'deviceStatus': 'off', 'connectionStatus': 'online', 'connectionType': 'wifi', 'deviceType': 'CS158-AF', 'type': 'SKA', 'uuid': '-----------------------------------', 'configModule': 'WiFi_AirFryer_CS158-AF_EU', 'macID': None, 'mode': None, 'speed': None, 'currentFirmVersion': None, 'subDeviceNo': None, 'subDeviceType': None, 'deviceFirstSetupTime': 'Nov 26, 2022 12:53:41 PM', 'subDeviceList': None, 'extension': None, 'deviceProp': None}]}}

2022-12-10 01:22:33,553 - DEBUG - New device list initialized
2022-12-10 01:22:33,554 - DEBUG - Unknown device named COSORI model CS158-AF
2022-12-10 01:22:33,554 - DEBUG - Error - 'VeSync' object has no attribute 'unknown'
2022-12-10 01:22:33,554 - DEBUG - CS158-AF device not added
True

**Comment by webdjoe** [comment]
This is in testing, please test branch #160 and let me know if you find any bugs

Also discussed in #55

**Comment by KyleStilkey** [comment]
How do we test this branch I've asked in the old thread and checking now as I have no idea how to update a built in integration.
