### ISSUE TITLE
KeyError: 'air_quality_value' - Core300s

### ISSUE THREAD

**Issue by dpensox** [webdjoe/pyvesync#173]
Hi,
I occasionally get the following error when calling the displayJson;

Traceback (most recent call last):
  File "D:\Projects\VesSyncStatus.py", line 45, in <module>
    print(device.displayJSON())
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\pyvesync\vesyncfan.py", line 602, in displayJSON
    {'Air Quality Value': str(self.details['air_quality_value'])}
                              ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 'air_quality_value'


The script sometimes works, and I do get a reading for air quality value, but every couple of executions I get this error.

**Comment by webdjoe** [comment]
That's very strange, it should be defined whether the API returns a value or not. I've used get instead of brackets to access, so it shouldn't be a problem anymore #160
