### ISSUE TITLE
Invalid key "virtual_mist_level" for VeSync Humidifer

### ISSUE THREAD

**Issue by chuckdeal97** [webdjoe/pyvesync#174]
On line 1292 of vesyncfan.py (https://github.com/webdjoe/pyvesync/blob/master/src/pyvesync/vesyncfan.py#L1280) there is a key reference for "virtual_mist_level" that should actually be "mist_level".  There are no other references to "virtual_mist_level" in the file.

**Comment by webdjoe** [comment]
I don't have one of these to test, do you know what the difference is between `mist_virtual_level` and `mist_level`?

**Comment by webdjoe** [comment]
Fixed in #160
