### ISSUE TITLE
Unable to get ESW01 to execute on/off commands

### ISSUE THREAD

**Issue by jmhartmann** [webdjoe/pyvesync#175]
I am new to this interface and I'm having issues getting going.  I successfully import the module, and log in to my VeSync account, where  I can see my device list. I have logged in enabling debug mode "manager = VeSync("myaccount@gmail.com", "mypassword", "us", debug=True)".
When I attempt to use the API I see errors in the debug output and I wonder if someone can point to anything I might have missed.

> >>> myplug.turn_on()
> 2023-01-15 23:20:30,886 - DEBUG - =======call_api=============================
> 2023-01-15 23:20:30,886 - DEBUG - [put] calling '/v1/wifi-switch-1.3/d87c6ad8-cb2c-4ba5-874f-9110a9b1ee7b/status/on' api
> 2023-01-15 23:20:30,887 - DEBUG - API call URL:
>   https://smartapi.vesync.com/v1/wifi-switch-1.3/d87c6ad8-cb2c-4ba5-874f-9110a9b1ee7b/status/on
> 2023-01-15 23:20:30,887 - DEBUG - API call headers:
>   {"accept-language": "en", "accountId": "1111111", "appVersion": "2.8.6", "content-type": "application/json", "tk": "opVI5rFhcz07NLY8Vg00CJTn2GiV-8QDuD66W2QwrMz9Lj-teg==", "tz": "us"}
> 2023-01-15 23:20:30,888 - DEBUG - API call json:
>   null
> 2023-01-15 23:20:31,151 - DEBUG - API response:
> 
>   {'error': {'code': 4001007, 'msg': 'request parameter invalid'}}
> 
> True
> >>>
>

**Comment by webdjoe** [comment]
Were you able to resolve this, it seems to be working as usually for that device on my end?

**Comment by jmhartmann** [comment]
Thanks Joe, I was not able to get it working. I would debug more if I knew
how. I'm not familiar with web interfaces/ debugging, being more an
embedded systems guy.

**Comment by webdjoe** [comment]
Ahh.. it should be `manager = VeSync("email@email", "password", "America/New_York", debug=True)` The time zone needs to be an [IANA](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) time zone

**Comment by jmhartmann** [comment]
Thank you, it is working now. I didn't understand the timezone parameter
correctly.
