### ISSUE TITLE
API down? 

### ISSUE THREAD

**Issue by jbrink90** [webdjoe/pyvesync#176]
Hey yall. Is the Vesync API down? I'm getting a 404 from my end. https://smartapi.vesync.com/

**Comment by webdjoe** [comment]
No, seems to be working fine on my end

**Comment by jbrink90** [comment]
Thanks for checking. Vesync support was surprisingly quick and helpful in explaining their certificate had expired and needed renewed. You were seemingly the lucky charm that fixed it @webdjoe.
