### ISSUE TITLE
Add support for turning on/off display on LV-PUR131S

### ISSUE THREAD

**Issue by JeffSteinbok** [webdjoe/pyvesync#182]
Would it be possible to add support for turning on and off the display on the LV-PUR131S?
Right now it comes back as an attribute (screen_status: off), but would like to be able to set it from HA as well.

**Comment by webdjoe** [comment]
Added to PR #183 - this is just the pyvesync library, HA will require the integration to be updated.

**Comment by JeffSteinbok** [comment]
This something you do?  Or an ask I need to make elsewhere?

**Comment by webdjoe** [comment]
Added to release [2.1.7](https://github.com/webdjoe/pyvesync/releases/tag/2.1.7) on pypi - the pyvesync version needs to be updated in HA to be able to use this. And the methods need to be referenced in the vesync component. That would be an HA issue

**Comment by JeffSteinbok** [comment]
@webdjoe What's the process for getting it fixed in HA?
