### ISSUE TITLE
Add Support for Humidifier LUH-O451S-WEU (Oasismist EU Version)

### ISSUE THREAD

**Issue by mjiines** [webdjoe/pyvesync#189]
It would be great if the LUH-O451S-WEU could be added. As far as i can tell it's just the EU Version of the Oasismist Humidifier.

Maybe just adding this line to the existing Oasismist should be enough. After all, the other devices also have their EU Version in the models. This should be easier than performing a packet capture and so on.

I don't have any experience though, so this might not work. But it would be nice since i don't live in the US and would like to use this device anyway.

**Comment by sid3windr** [comment]
I'm using OpenHAB which has a binding based off pyvesync, and I have the WEU model. Can confirm it works identically to the WUS version, if that helps.

**Comment by mjiines** [comment]
I am using Homeassistant and accessing Vesync Devices with the Help of this [Custom Integration](https://github.com/vlebourl/custom_vesync). If the binding in OpenHAB references pyvesync as well, than i wonder why it would work there but not in HA.

I will however give it a try. I would need to install OpenHAB in a VM and connect it to HA to control the Device, but if that works and OpenHAB does not draw too much CPU, than i could get by with that method. Hopefully though this line could get added to simplify the Setup a bit.

You wouldn't happen to know how i could fork [this Integration](https://github.com/vlebourl/custom_vesync) and pyvesync and just add the line myself. Because i tried but HA didn't find the pyvesync dependency.

**Comment by mjiines** [comment]
I just installed OpenHAB (3.4.4) and added the vesync Binding. Unfortunately it does not find the Humidifier, it picks up any other device like my air purifier automatically though. I've even tried changing regions in the Vesync app. Did you make any other changes, or just installed the binding, added the bridge and from there the humidifier?

**Comment by sid3windr** [comment]
Ah, there's a catch which I forgot to mention there. The Oasis Mist support is not in an OH release (except I presume the 4.x pre-releases). I got the binding jar file from the developer's topic (https://community.openhab.org/t/levoit-binding/127930/71) and that one does recognize the humidifier. Sorry for not mentioning that, I wasn't assuming you'd actually be installing OpenHAB :D

**Comment by mjiines** [comment]
So, i was messing around a bit with pyvesync. As i said i am using Homeassistant to control my devices. I want to control the humidifier with [custom_vesync](https://github.com/vlebourl/custom_vesync) which uses pyvesync in the backend.

I can now control my humidifier from the Command Line in HA (which isn't very useful though) when importing my modified repository of pyvesync (just added the WEU to the models). However it is not listed in HA when i install the Integration. Other than for example my Core400s

Now i can't tell if that's because of custom_vesync or pyvesync. But i can say then by adding the WEU model, it theoretically works.

Still, would be nice if it could get added to this repo.

**Comment by dag81** [comment]
Hi I saw this, while trying to find other data. So I ported some of the great work from pyvesync to openhab. Only the 3.5 version has the latest version (as only bugfix can be back ported not new additions). The build referenced, basically does matching. So

LAP-C601S-WUS, LAP-C601S-WEU

is matched by LAP-C601S excluding the final part. The WEU version otherwise will be using the same protocols that were mapped by pyvesync against the WUS version. If the user has confirmed WEU is running the same as the others you have. Hopefully that helps (I should add its re-written to optimize it for OpenHab so its not a wrapper around pyvesync - that's one of the bits optimised - as I don't have a lot of free time always to update the model identification - where its just region codes - and so far all regions have performed identically for air purifiers and air humidifiers).

**Comment by webdjoe** [comment]
Thank you, I will include this in next release this weekend!

**Comment by mjiines** [comment]
That's great.
I've forgot to post here. I've added the line manually. (Had to mount Docker Volume via HA Terminal etc.)

I can confirm that this actually works. So it's nice to see this added to the official repository.

There's one thing i noticed. The control for the Humidifier seems a bit lagged. Though the Mist Level and on off works fine. Just the reporting of the state is a bit slow. But i have no idea if that's because of pyvesync or the HA/Integration being Slow. It seems to work fine when in Terminal though, so my guess is that it's not pyvesync.

**Comment by webdjoe** [comment]
Released in 2.18 available on pypi!
