### ISSUE TITLE
Add support for Nightlight functionality on OasisMist

### ISSUE THREAD

**Issue by sid3windr** [webdjoe/pyvesync#190]
I have an OasisMist (LUH-O451S) which has nightlight functionality, working from within the app. But it seems pyvesync does not yet support the nightlight color and on/off functionality on this model. Would it be possible to add this?

Available for testing if necessary of course.

Thanks!

**Comment by webdjoe** [comment]
I don't have this device myself. If you can capture packets, I'm happy to add
