### ISSUE TITLE
Check master branch - suspected error for air purifiers

### ISSUE THREAD

**Issue by dag81** [webdjoe/pyvesync#197]
Hi @webdjoe,

I suspect there is a mistake in main.

https://github.com/webdjoe/pyvesync/blob/2d70bb4c12cdd2c64243aa62a4cd6b0548c99a04/src/pyvesync/vesyncfan.py#L109

has the same model LAP-V1025-AUSR, as

https://github.com/webdjoe/pyvesync/blob/2d70bb4c12cdd2c64243aa62a4cd6b0548c99a04/src/pyvesync/vesyncfan.py#L101

I suspect this is a mistake and the models should appear only once for one entry in the dict?

I suspect L109 should be if its a copy / paste / edit error like I suspect?

 'LAP-V201S-AUSR', 'LAP-V201S-WUS'],

Sorry adding another bit - you have these two lines for the Vital handler:

https://github.com/webdjoe/pyvesync/blob/2d70bb4c12cdd2c64243aa62a4cd6b0548c99a04/src/pyvesync/vesyncfan.py#L821

https://github.com/webdjoe/pyvesync/blob/2d70bb4c12cdd2c64243aa62a4cd6b0548c99a04/src/pyvesync/vesyncfan.py#L824

It looks like L824 overwrites L821, so I guess L821 is not required, if this has been tested, unless there's some python trick I'm missing here. Just noticed however the same screenState is assigned to something else as well, so not quite sure what's out here but I suspect something.

https://github.com/webdjoe/pyvesync/blob/2d70bb4c12cdd2c64243aa62a4cd6b0548c99a04/src/pyvesync/vesyncfan.py#L830

Sorry another observation for review:

https://github.com/webdjoe/pyvesync/blob/2d70bb4c12cdd2c64243aa62a4cd6b0548c99a04/src/pyvesync/vesyncfan.py#L917

Both the manuals for the Vital 100S and 200S have a screen lock icon, so I think this is applicable to both models?

**Comment by webdjoe** [comment]
Fixed in #198
