### ISSUE TITLE
Auto Mode not in API

### ISSUE THREAD

**Issue by byrdman7735** [webdjoe/pyvesync#209]
I have a Core 400S and everything works great.
I purchased a new Core300S and they support Auto Mode now. When I try and switch it I receive this error.
       Fan mode command for "auto" is not valid in the (Core200S/Core300S) API possible options manual,sleep
Looks like Auto Mode needs to be added to the API for the Core 300S.

**Comment by webdjoe** [comment]
Can you test this on the latest version of HA, it should work now

**Comment by webdjoe** [comment]
This should be fixed in the latest release, please open a new PR if you are still having issues
