### ISSUE TITLE
Add Support - OasisMist LUH-O451S-WUSR

### ISSUE THREAD

**Issue by hmin03** [webdjoe/pyvesync#211]
Purchased this from a US Best Buy and assume the model number indicates the retail version with the addition of the R at the end.  Hopefully an easy fix to add that to the list array within **vesyncfan.py**.

### Currently:
['LUH-O451S-WUS', 'LUH-O451S-WEU']

### Requested:
['LUH-O451S-WUS', 'LUH-O451S-WUS**R**', 'LUH-O451S-WEU']

**Comment by hmin03** [comment]
Sorry, completely forgot to state the problem:
Device is not detected by the Home Assistant HACS integration.

**Comment by webdjoe** [comment]
This is in release 2.1.12 now on pypi
