### ISSUE TITLE
Add Support for Levoit Superior 6000S Smart Evaporative Humidifier

### ISSUE THREAD

**Issue by adamckbatchelor** [webdjoe/pyvesync#214]
As title says, add support for the Levoit Superior 6000S Smart Evaporative Humidifier (Model Number: LEH-S601S-WUS)

Currently not detected by the Home Assistant HACS Vesync integration.

**Comment by tkamenick** [comment]
I want support for this model as well. I was struggling to get the request capture working, but finally got it figured out today and quickly added support for most of the api surface. I'm still working on adding a few of the write apis and will submit a PR when finished.

**Comment by webdjoe** [comment]
@tkamenick thank you

**Comment by webdjoe** [comment]
Thank you for the PR, merged and released v1.1.12
