### ISSUE TITLE
Add Support for OasisMist600s

### ISSUE THREAD

**Issue by ModeratePrawn** [webdjoe/pyvesync#219]
Hello, 

Respectfully requesting the addition of the OasisMist 600 S from Levoit. I have one, and would be willing to test for you, if you need it.

**Comment by webdjoe** [comment]
There is a chance this is already supported, what is the model number? Use the `debug` argument when instantiated the `VeSync` object

**Comment by DJaeger** [comment]
The Levoit OasisMist 600S seems to be 6L variant of the Levoit OasisMist 450S (LUH-O451S-WUS): 
https://levoit.com/products/levoit-oasismist-600s
https://levoit.com/products/oasismist-smart-humidifier

The model as of website is:
LUH-O601S-KUS

I have made a PR (#244) for this model

**Comment by webdjoe** [comment]
Thank you for the PR! This should be included in the latest release, please reopen if there is still an issue.
