### ISSUE TITLE
Add Support for LV6S model LUH-A602S-WUSC - Not Detected by Home Assistant

### ISSUE THREAD

**Issue by ziptbm** [webdjoe/pyvesync#220]
I just got an LV6S model LUH-A602S-WUSC and it is Not Detected by Home Assistant.

is there information I can pull on my end to assist in adding support?  It’s my understanding this model is very similar to the LV600s.  Thanks!

**Comment by h-parks** [comment]
I would really like to see support for this model as well!

**Comment by webdjoe** [comment]
This will be released shortly in v1.1.12

**Comment by webdjoe** [comment]
Released!
