### ISSUE TITLE
Added support for European version of Vital200S PRO

### ISSUE THREAD

**Issue by Po3uk** [webdjoe/pyvesync#224]
I would need to add this support. When adding a line for LAP-201S-AEUR, everything works, but the PET mode is not available.

**Comment by onurchaner** [comment]
Yes please add LAP-201S-AEUR

**Comment by webdjoe** [comment]
Is it LAP-201S-AEUR or LAP-V201S-AEUR?

**Comment by Po3uk** [comment]
Yes it's LAP-V201S-AEUR.

**Comment by webdjoe** [comment]
Added to release 2.12
