### ISSUE TITLE
Add support for reseting filter life for purifiers

### ISSUE THREAD

**Issue by ljmerza** [webdjoe/pyvesync#226]
The app requires you to go into the filter settings for each purifiers which is kind of tedious. It would be very helpful to be able to call functions that can reset the filter life for purifiers. Thank you.

**Comment by blenk92** [comment]
Hey, I faced the same issue and proposed this MR https://github.com/webdjoe/pyvesync/pull/232. Maybe it helps you as well...

**Comment by ljmerza** [comment]
Awesome I will check it out and try locally when I get a chance. Thanks!

**Comment by webdjoe** [comment]
This has been merged and released on pypi v2.1.11. Thank you for the PR!
