### ISSUE TITLE
Fan Speed with Levoit  Air Purifier 200s not working

### ISSUE THREAD

**Issue by sturowski** [webdjoe/pyvesync#236]
I'm using a Levoit Air Purifier 200s with openHAB 4.1.2. After adding the VeSync Bridge it's detected my three devices without problem. I created a model for one of them and linked the following channels:

- Switched On
- Filter Life Remaining
- Operation Mode
- Fan Speed

The first three are working without problems. Mabye there is one failure, i can set the Operation Mode to "Auto" thats not possible with the 200s but it's ok.

If I want to change the Fan speed openHAB always opens a chart and no selection. 
![image](https://github.com/webdjoe/pyvesync/assets/22936799/cdc34cb6-5f3b-4c92-ac08-0e1f8de6d57d)
![image](https://github.com/webdjoe/pyvesync/assets/22936799/372fced3-6809-4e7b-8a86-557d06db7c05)
Can you help me?

And I always see "NULL" as State:
![image](https://github.com/webdjoe/pyvesync/assets/22936799/9c6e73c3-5e58-473e-b9af-9fd37b583e95)

**Comment by webdjoe** [comment]
Is there an associated error message or log entry? I will leave this issue open for a bit to see if anyone has a similar issue but I would recommend trying on the OpenHAB forum.

**Comment by webdjoe** [comment]
I'm closing this issue because it is an OpenHAB integration issue. Please open a new issue if there are any errors from this library. Thank you!
