### ISSUE TITLE
Deprecated method that will stop working on HASS 2025.1

### ISSUE THREAD

**Issue by hernaj** [webdjoe/pyvesync#254]
It seems some parts of code will stop working on HASS 2025.1

Origin:
homeassistant.helpers.frame
helpers/frame.py:155

Detected code that calls async_forward_entry_setup for integration vesync with title: XXXXX, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

**Comment by cdnninja** [comment]
This is a library.  Not the integration. I suspect this is reported in the wrong spot.

**Comment by webdjoe** [comment]
Thank you @cdnninja , closing this issue
