### ISSUE TITLE
Potential typo in source code?

### ISSUE THREAD

**Issue by dag81** [webdjoe/pyvesync#255]
Hi, Is this intentionally without the S on this end? It looks like a typo? 

LAP-V201-AUSR

https://github.com/webdjoe/pyvesync/blob/2a9b7a0bad889d7226bedf18c7c1961ebfe28b7d/src/pyvesync/vesyncfan.py#L135

**Comment by webdjoe** [comment]
There are many different `configModule` names from different geographic regions and versions of the devices, many of which I do not personally have. I will remove if it is causing an issue, but I'd rather leave it in to not cause a breaking change.
