### ISSUE TITLE
Does not report newer 15AMP outlets

### ISSUE THREAD

**Issue by jlboygenius** [webdjoe/pyvesync#3]
Hi mark, Not sure if you read these. The new 15Amp outlets use a different API.
Another user used your code as a starting point and added in support for the correct power calculation and to support the new outlet types.

https://github.com/webdjoe/pyvesync-v2

**Comment by markperdue** [comment]
I've refactored the code a bit quite a lot in a branch to better support new models of switches being released. I also picked up the 15a switch and implemented it in a feature branch that I'll merge into master once I get my pypi workspace up and running again. @webdjoe has been fantastic and provided a lot of api call data around switches and devices I do not have so I'm hoping to work with him to get additional devices introduced to this library

**Comment by markperdue** [comment]
code has been merged. the 15a switches are now supported.
