### ISSUE TITLE
LV-PUR131S Home Assistant Integration

### ISSUE THREAD

**Issue by webdjoe** [webdjoe/pyvesync#33]
Hey guys. Great library here and glad that you're integrating with Home Assistant. I too have the LV-PUR131S. Right now, it's not at all detected in Home Assistant. In fact, it looks like the module fails to load in HA and it looks like it's erroring on all the "fan" related functions.

_Originally posted by @metril in https://github.com/markperdue/pyvesync/issues/31#issuecomment-500264480_

**Comment by zlalanne** [comment]
Another LV-PUR131S + Home Assistant user here. Happy to help out testing/developing/documenting. Is there a branch right now with LV-PUR131S development for Home Assistant?

**Comment by webdjoe** [comment]
Thanks @zlalanne, that would be great.  I should have an HA component beta branch shortly.  Meanwhile, if you wouldn't mind testing the library out, to make sure the fan methods are working properly and see if there are any features or properties that should be added.  You can download the master branch and just use easy install to set it up from the command line.  Let me know if you want me to put together a testing script.

**Comment by zlalanne** [comment]
FYI just opened PR #34

**Comment by metril** [comment]
I'm getting some errors shown below. I also get an invalid configuration, but that doesn't make sense. I have the VeSync username and password prescribed as noted in the wiki.

`2019-06-23 15:47:22 ERROR (MainThread) [homeassistant.setup] Error during setup of component vesync
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 156, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/vesync/__init__.py", line 35, in setup
    manager.update()
  File "/usr/local/lib/python3.7/site-packages/pyvesync/vesync.py", line 188, in update
    outlets, switches, fans = self.get_devices()
  File "/usr/local/lib/python3.7/site-packages/pyvesync/vesync.py", line 135, in get_devices
    outlets, switches, fans = self.process_devices(device_list)
  File "/usr/local/lib/python3.7/site-packages/pyvesync/vesync.py", line 105, in process_devices
    fans.append(VSFactory.getDevice(devType, dev, self))
  File "/usr/local/lib/python3.7/site-packages/pyvesync/vesync.py", line 31, in getDevice
    return VeSyncAir131(config, manager)
  File "/usr/local/lib/python3.7/site-packages/pyvesync/vesyncfan.py", line 9, in __init__
    self.filter_life = {}`

**Comment by webdjoe** [comment]
In terms of the invalid configuration, I can't say what's going wrong. I have it working.  Can you post exactly what you have in your config, space for space?  This won't be an issue once I finish the built in component.  You will be able to configure it through the frontend UI.

Are you showing a percent remaining filter life in the app?

**Comment by metril** [comment]
> In terms of the invalid configuration, I can't say what's going wrong. I have it working. Can you post exactly what you have in your config, space for space? This won't be an issue once I finish the built in component. You will be able to configure it through the frontend UI.
> 
> Are you showing a percent remaining filter life in the app?

I am seeing a filter percent remaining the Vesync app. I can control the purifier in the app as well.

I have tried putting the Vesync config in two different ways:

### **Method A**
`# Example configuration.yaml entry
switch:
  - platform: vesync
    username: YOUR_USERNAME
    password: YOUR_PASSWORD`

and also as the following directly in the configuration.yaml file.

### **Method B**
`vesync:
  username: VESYNC_USERNAME
  password: VESYNC_PASSWORD`

I have also tried putting the following in a separate switches.yaml file and referencing the switches.yaml in the configuration.yaml file. As follows:

### **Method C**
`switch: !include switches.yaml`

switches.yaml content:

`- platform: vesync
    username: YOUR_USERNAME
    password: YOUR_PASSWORD`

None of the above methods work while there are any custom vesync components (files as prescribed in the repository, git cloned and specific files copied over).

### ** The error for Method A and Method C is as follows:**

`2019-06-28 19:32:40 ERROR (MainThread) [homeassistant.setup] Error during setup of component vesync
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 156, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/vesync/__init__.py", line 26, in setup
    conf = config[DOMAIN]
KeyError: 'vesync'`

If I remove the custom components and allow Hassio to use the built-in Vesync, then there are no errors. However, I do not have any Vesync compatible items other than purifier so there is no way for me to really check this.

Method B gives me errors regardless of built-in Vesync or custom components Vesync and is as posted previously.

Additionally, the Vesync username is an email address (20 characters). The Vesync password (16 characters) is alpha-numeric with upper and lower case characters. There are no special characters. I have tried putting this with and without single or double quotes to emphasize string.

**Comment by webdjoe** [comment]
This cannot be set up as individual platforms (light, switch, fan, etc), just the vesync component.  You should have this exact formatting in your config, no extra spaces or punctuation:
```
vesync:
  username: YOUR_USERNAME
  password: PASSWORD
```

**Comment by metril** [comment]
I initially tried that. I tried it again and I am getting the same errors as before.

`2019-06-29 12:58:24 ERROR (MainThread) [homeassistant.setup] Error during setup of component vesync
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 156, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/vesync/__init__.py", line 35, in setup
    manager.update()
  File "/usr/local/lib/python3.7/site-packages/pyvesync/vesync.py", line 188, in update
    outlets, switches, fans = self.get_devices()
  File "/usr/local/lib/python3.7/site-packages/pyvesync/vesync.py", line 135, in get_devices
    outlets, switches, fans = self.process_devices(device_list)
  File "/usr/local/lib/python3.7/site-packages/pyvesync/vesync.py", line 105, in process_devices
    fans.append(VSFactory.getDevice(devType, dev, self))
  File "/usr/local/lib/python3.7/site-packages/pyvesync/vesync.py", line 31, in getDevice
    return VeSyncAir131(config, manager)
  File "/usr/local/lib/python3.7/site-packages/pyvesync/vesyncfan.py", line 9, in __init__
    self.filter_life = {}`

**Comment by webdjoe** [comment]
Ah, that is a bug in the old pypi package.  If you are running on anything except hass.io, you can update the python package manually from this repo. I will try to update the package on pypi shortly

**Comment by metril** [comment]
How do I get the updated package into Hassio after you update it?

**Comment by webdjoe** [comment]
You just copy over the updated manifests.json file with the new version

**Comment by metril** [comment]
I am clearly doing something wrong, but I do not know what.

`Unable to install package pyvesync==1.0.11: ERROR: Could not find a version that satisfies the requirement pyvesync==1.0.11 (from versions: 0.1.0, 0.1.1, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.0.10)
ERROR: No matching distribution found for pyvesync==1.0.11`

**Comment by webdjoe** [comment]
Your not doing anything wrong, it hasn't been uploaded on pypi.  It should be up sometime tonight

**Comment by webdjoe** [comment]
Package uploaded to pypi version 1.0.11  and PR submitted to HA - https://github.com/home-assistant/home-assistant/pull/24953
