### ISSUE TITLE
Consider matching repository layout needed for HACS

### ISSUE THREAD

**Issue by zlalanne** [webdjoe/pyvesync#35]
The [HACS](https://custom-components.github.io/hacs/) project allows you to install and manage custom components. There is a [blueprint](https://github.com/custom-components/blueprint) of what the repository layout should look like.

**Comment by webdjoe** [comment]
Wow that's a really cool add-on, thanks for the tip. I'm trying to make this component an integration that uses the config flow in the frontend, which can't be done with custom components.  So you won't need to put your login info in configuration.yaml.  I pretty much have it done, just putting some finishing touches.  I should have a PR with HA shortly: 
![image](https://user-images.githubusercontent.com/8164486/60405718-0bf16780-9b80-11e9-8997-3c36ff07bb66.png)
![image](https://user-images.githubusercontent.com/8164486/60405735-2a576300-9b80-11e9-857b-4779d704662c.png)

**Comment by zlalanne** [comment]
So long term this is meant to be updated in Home Assistant and not live as a custom component?

**Comment by webdjoe** [comment]
Yes it will be built-in HA, should hopefully have a PR out soon.  There is a Vesync component already built-in but it's an older version  with support for only a few of the original devices

**Comment by webdjoe** [comment]
PR submitted to HA - https://github.com/home-assistant/home-assistant/pull/24953
