### ISSUE TITLE
latest firmware version?

### ISSUE THREAD

**Issue by Ramarc** [webdjoe/pyvesync#37]
Feature request: It would be great if the version number of the newest firmware was also available with current_firm_version for each outlet. It would be helpful to determine if a device has old firmware without opening the app.

I took a look at the vesync apk to try and find an api call. The closest I could find might be:

o.wifiOutletType()+"/v1/device/firmwarestatus.

**Comment by webdjoe** [comment]
Feature added, will be in next release - https://github.com/markperdue/pyvesync/pull/38
