### ISSUE TITLE
Any idea on how to make ESL100CW work?

### ISSUE THREAD

**Issue by momo1** [webdjoe/pyvesync#41]
Hi,

This is not an issue with the library but I'd appreciate any input! I've been trying to figure out how to make the ["Tunable" bulb](https://www.amazon.com/dp/B07NR514SD/) to work with no luck. All the `SmartBulb/` APIs work except for the `/devicestatus`. When I try to PUT the new status it hangs for a while then I get an error message that "the device is not responding" (according to Google translate). POST just causes an "internal module error"

I also tried to use all the other APIs for all other devices that I could find in this library and by inspecting the app, none of them worked. It seems I'm missing something stupidly simple.

This is the request that hangs: (omitting all headers):

```
PUT https://smartapi.vesync.com/SmartBulb/v1/device/devicestatus
{
  "timeZone":"America/New_York",
  "acceptLanguage":"en",
  "accountID":"XXXXXXX",
  "token":"XXXXXXXXXXXXX",
  "uuid":"XXXXXXXXXXXXX",
  "status":"on",
  "brightness":"100"
}
```
The response:
```
{
  "code": 4041005,
  "msg": "设备未响应",
  "traceId": "1565073187628",
  "result": null
}
````

For more information about the device, this is an excerpt of what I get when I `POST https://smartapi.vesync.com/cloud/v1/deviceManaged/devices`

```
 {
      "deviceRegion": "US",
      "deviceName": "Bedroom",
      "deviceImg": "https://smartapi.vesync.com/v1/app/imgs/icon_dimmable_bulb/icon_white_light_bulb.png",
      "cid": "XXXXXXXXXXXXXXXXXXXXX",
      "deviceStatus": "off",
      "connectionStatus": "online",
      "connectionType": "wifi",
      "deviceType": "ESL100CW",
      "type": "Wifi-light",
      "uuid": "XXXXXXXXXXXXXXXXXXXXXX",
      "configModule": "WiFi_Bulb_WhiteLightBulb_US",
      "macID": null,
      "mode": null,
      "speed": null,
      "extension": null,
      "currentFirmVersion": null,
      "subDeviceNo": null
    }]
```
Any ideas?

Thanks!

**Comment by webdjoe** [comment]
Your hitting the `/SmartBulb/` endpoint which is only for the ESL100.  Each device has it's own endpoint.  You can try different combinations, such as `/TunableBulb/`, `/CTWLBulb/`, etc. but you would also have to figure out the call structures by trial and error.  The best way would be to load the VeSync App up on an Android device or Android Emulator and use a packet capturing app to catch the traffic.  I have had success with this one (no root required) 
 https://play.google.com/store/apps/details?id=app.greyshirts.sslcapture&hl=en_US 

Just start capturing for the VeSync app, load the device list and try using all of the controls for that bulb.  You can paste the results here and I'll see if I can add it into this library.

**Comment by momo1** [comment]
Thanks Joe! I tried all of routes with the expected payload that I found in the app (it's just a ReactNative JS file) I wasn't blindly going over them :) But here's the thing, using the Packet Capture tool I was able to find out where I went wrong with the route that was supposed to work. I missed part of the payload. Thank you for referring me to that tool I didn't know we could capture SSL without root.

Yislamo!

**Comment by webdjoe** [comment]
Glad I can help, if you want to post those calls I will work on integrating it into this library

**Comment by momo1** [comment]
Sure. Here you go:

POST https://smartapi.vesync.com/cloud/v1/deviceManaged/bypass

```
{
  "acceptLanguage": "en",
  "accountID": "XXXXXX",
  "appVersion": "2.8.4",
  "timeZone": "America/Los_Angeles",
  "token": "XXXXXXXXXX",
  "uuid": "XXXXXXXXXX",
  "cid": "XXXXXXXXXXX",
  "configModule": "WiFi_Bulb_WhiteLightBulb_US",
  "jsonCmd": {
    "light": {
      "action": "off"
    }
  },
  "method": "bypass",
  "traceId": "--------------",
  "phoneBrand": "SomePhone",
  "phoneOS": "Android 8.0.0"
}
```
