### ISSUE TITLE
example code

### ISSUE THREAD

**Issue by SESNut** [webdjoe/pyvesync#42]
Im trying to run the example code in python 3.4 and it errors out with
Traceback (most recent call last):
  File "C:\Users\sesnu\Desktop\z.py", line 1, in <module>
    from pyvesync import VeSync
  File "C:\Python34\lib\site-packages\pyvesync\__init__.py", line 1, in <module>
    from .vesync import VeSync
  File "C:\Python34\lib\site-packages\pyvesync\vesync.py", line 5, in <module>
    from pyvesync.helpers import Helpers as helpers
  File "C:\Python34\lib\site-packages\pyvesync\helpers.py", line 64
    **cls.req_body_base(manager),
     ^
SyntaxError: invalid syntax

**Comment by webdjoe** [comment]
Only python 3.5+ is supported.  Try to run it with a newer version of python

**Comment by SESNut** [comment]
get_devices only returns [] [] [] []

is there any way to call a device via cid or uuid and not list value?

**Comment by webdjoe** [comment]
You should be calling `manager.update()`, not `manager.get_devices()` to pull the devices from the server.

If that doesn't work, set logging level to debug and see if there are any errors.  There should be at least one if all of your device lists are empty.  What device are you using and is it already set up in the app?

If your asking if you could just pass a CID or UUID to control a device without the manager instantiating the device objects, the answer is no.  Each device has different api endpoints and call structures that are set from the device info when you call `manager.update()`.  

If your `manager.outlets`, `manager.switches`, etc. are already populated, you can use any device attribute to call a specific device.

```python
device_cid = "DEV_CID"
for outlet in manager.outlets:
    if outlet.cid == dev_cid:
        outlet.turn_on()
```

**Comment by SESNut** [comment]
alright thanks for the info, that was really helpful
