### ISSUE TITLE
Feature Request: Expose nightlight status

### ISSUE THREAD

**Issue by bwarden** [webdjoe/pyvesync#47]
In the details dict, I can see the following nightlight entries (for the 15A outlet):
- night_light_automode
- night_light_status
- night_light_brightness

It would be nice to expose these through the API, or at least a reasonable assessment of whether the nightlight is on or off.

https://github.com/markperdue/pyvesync/blob/5cf2c8b667aae0dd7b82d93619f277fc6e7c8800/src/pyvesync/vesyncoutlet.py#L376

**Comment by webdjoe** [comment]
Added to next PR - https://github.com/markperdue/pyvesync/pull/49
