### ISSUE TITLE
Add Sleep mode to fan speeds or an action to call sleep mode

### ISSUE THREAD

**Issue by ThirteenTX** [webdjoe/pyvesync#52]
I can't seem to figure out how to call sleep mode for the device. Auto mode is a fan speed but sleep is not even though it seems to just be a really low speed. Is there some way to call it or is there any way it can just be a speed? This is for the air purifier.

**Comment by ThirteenTX** [comment]
Also it would be cool if you could turn off the display via automation. Thanks for getting this working in the first place! If it doesn't work I can manage it would just be nice.

**Comment by webdjoe** [comment]
Added the methods to turn display on/off in my repo - https://github.com/webdjoe/pyvesync_v2/pull/16
