### ISSUE TITLE
Air quality doesn't return in percentage in Home Assistant

### ISSUE THREAD

**Issue by haroutig** [webdjoe/pyvesync#54]
The air quality value for the air purifier returns as a string (eg "excellent") instead of a percentage in home assistant. A percentage would be much better here as the air quality can be integrated properly into the home app on ios.

**Comment by webdjoe** [comment]
What are the different air quality properties?

**Comment by ronytomen** [comment]
Wouldn't the conversion be the responsibility of the Home Assistant so that different "definitions" could be country or region aware?

**Comment by borpin** [comment]
@haroutig - can you use the library directly and see what value is actually returned by the API? Is it definitely a number that is returned?

**Comment by jetpacktuxedo** [comment]
I think this is actually fixed as of 2.X, and there is a fix merged on the homeassistant side that should release in the 2022.7 release.

**Comment by borpin** [comment]
> I think this is actually fixed as of 2.X, and there is a fix merged on the homeassistant side that should release in the 2022.7 release.

The last time I looked at the core PR, it did not provide as much functionality as this add-on.

**Comment by webdjoe** [comment]
This should be fixed, closing issue
