### ISSUE TITLE
Can you update pip with Version 1.2?

### ISSUE THREAD

**Issue by bbaros** [webdjoe/pyvesync#57]
Current version in pip and Home Assistant is 1.1.  Seems like dimmer support works only in 1.2.  Can you update pip and home-assistant-core/requirements_all.txt to version 1.2?

**Comment by djtimca** [comment]
PR has been submitted in Home Assistant with bumped version https://github.com/home-assistant/core/pull/40978

**Comment by webdjoe** [comment]
Updated to 1.2.1

**Comment by djtimca** [comment]
I have submitted PR to Home Assistant with bump in dependency to 1.2.1
