### ISSUE TITLE
ESWL03 Switch Not Supported Properly

### ISSUE THREAD

**Issue by HyperCharlie** [webdjoe/pyvesync#67]
We finally figured out the issue I was having in the Webthings Etekcity adapter- turns out the 3-way switches are a different device from the single switch and not supported properly by pyvesync! Here's the original issue, for context: https://github.com/WebThingsIO/etekcity-adapter/issues/8.

I have 2 ESWL01 switches and then added 2 more ESWL03 switches, not realizing there was any meaningful difference between them. Apparently there is a missing spot in pyvesync for the ESWL03.

**Comment by mrstegeman** [comment]
It's supported in the code [here](https://github.com/markperdue/pyvesync/blob/1ea24e2fcbb5878fa31157970b2091c3746c3f97/src/pyvesync/vesync.py#L30), but not [here](https://github.com/markperdue/pyvesync/blob/master/src/pyvesync/vesyncswitch.py#L11-L14).

**Comment by webdjoe** [comment]
I never tested my three way switches and I can't seem to find them right now. Can you please test? I added it to this fork here:

https://github.com/webdjoe-bot/pyvesync

**Comment by HyperCharlie** [comment]
Testing it now

**Comment by HyperCharlie** [comment]
Just successfully looped over the devices, and did a turn_on() sleep(2) turn_off() cycle on each. 3 way switch worked fine!

**Comment by HyperCharlie** [comment]
Hold up, if I call is_dimmable() on the 03 it's an issue, even with the entry in feature_dict. I'm working on it.

**Comment by HyperCharlie** [comment]
N/M, with fix it works fine; I had a conflict between the code from your fork and a pre-installed pyvesync. It seems to be all good!

**Comment by mrstegeman** [comment]
@webdjoe are you planning to merge this fix?

**Comment by webdjoe** [comment]
I'm finishing up a project at work so I'm hoping to have some time tonight
or this weekend.

**Comment by webdjoe** [comment]
Merged and uploaded to PyPi!
