### ISSUE TITLE
Support for Core 400s

### ISSUE THREAD

**Issue by bwalshin** [webdjoe/pyvesync#81]
Thank you so much for the hard work being done here. I’ve been using this for a while now with some other Levoit/Vesync products in Home Assistant and love it!

I just bought the Core 400s, but it doesn’t seem to be supported. From what I can tell, it has the same functionality as the Core 200s, just handles a larger space.

I noticed the Core 200s was recently added and was wondering if there is a way to add support for the Core 400s as well?

**Comment by Varjo1** [comment]
Seconded, this would be a great addition (also hoping to bring this into HA).

**Comment by Varjo1** [comment]
Actually, I took a quick stab at this (but I don't yet have a Core400S to test with). @bwalshin would you be willing to give PR #82 a try and see if it works for you?

**Comment by bwalshin** [comment]
@Varjo1 
Thank you so much for helping with this. 

I'm not as familiar with Python and not fully sure how to best get the code in a testable state. I've been doing the "learn as you go" approach with this, but haven't found the right setup from google that works for me.

Do you have any suggestions or applications I can try for a Mac?

**Comment by hungnguyenm** [comment]
Added and merged in #84 :).

**Comment by shermansmith** [comment]
Is the 400S going to be supported in the version of the integration that's available through Home Assistant? Right now it sort of detects it - entity only, no device present, and only tracks entity state (home or away).

**Comment by stealthlego** [comment]
I am defs a novice at all this, but my understanding is similar changes (to the included link) would need to be made on the home assistant vesync component would required. And I would imagine a small version change/update on pyvesync as well to force the pull in of the update including 400s support.

https://github.com/home-assistant/core/commit/3b3d6e0da53db2a0c9a65a649776ac3bd4e8906f

**Comment by bmorgan99** [comment]
Hoping this makes it to HA soon.  My phone is maxed out with one trick apps 🤞

Keep up the good work

**Comment by jparchem** [comment]
I was testing the new pyvesync changes for the Core400s in the latest build of Home Assistant.  

What I noticed is that when  pyvesync's `manager.update` is called, the fans collection list that is returned doesn't include my 400s (but my 200s is returned).  Both are present in the native VeSync application.  Any ideas why the 400s wouldn't be there?

**Comment by jparchem** [comment]
Also trying to determine the correct procedure to get these changes into Home Assistant?  pip/pip3 installs the older packages without support for the Core400s (or anything after late April, for that matter).    

FWIW I tested using the dev build of HA and manually updating the pyvesync library to the latest version.  I wasn't able to see the air quality measurement entity, but I could turn the 400s on/off and change the fan speed.  Good enough of a start for me.

**Comment by formatBCE** [comment]
I just added support for Core400S in my own fork of HA VeSync integration.
Unfortunately, due to lack of version bump, i had to include pyvesync code base into integration itself, so for now it does use local copy of lib code. I will update code, once new library version is available in pip.
Also, added Core300S there, adding pull request code #88.
If you eager to try it, here it is: https://github.com/formatBCE/HA_VeSync_Classic300s/tree/pyvesync_included

**Comment by jparchem** [comment]
> I just added support for Core400S in my own fork of HA VeSync integration.

@formatBCE How did you get that into HA?  Using HACS?  Since I run within a container, I can’t readily install via pip, and even if I get access to the container, it’s my understanding that the next time HA is updated I’ll lose those changes. 

Of course an official update would solve all of this for us.

**Comment by formatBCE** [comment]
> > I just added support for Core400S in my own fork of HA VeSync integration.
> 
> @formatBCE How did you get that into HA?  Using HACS?  Since I run within a container, I can’t readily install via pip, and even if I get access to the container, it’s my understanding that the next time HA is updated I’ll lose those changes. 
> 
> Of course an official update would solve all of this for us.  

I forked official VeSync integration, and replaced dependency to pyvesync with code files from GitHub (just included files).
So to have it, it should be placed to custom_components manually - similar to HACS approach. But it doesn't depend on external libraries now, except of core ones.

**Comment by webdjoe** [comment]
Just waiting on testing of the latest branch and I will bump!

**Comment by jparchem** [comment]
@formatBCE Thanks, it worked perfectly!

@webdjoe Thanks, Joe for creating this integration.  I appreciate the effort it takes.  I would be glad to assist with testing or any other tasks that would help.

**Comment by formatBCE** [comment]
> @formatBCE Thanks, it worked perfectly!
> 
> @webdjoe Thanks, Joe for creating this integration.  I appreciate the effort it takes.  I would be glad to assist with testing or any other tasks that would help.

No problem.
Once library will be available in pip with all updates, I will make changes to main branch, including new version dependency, to keep code clean. If you find that all-in-one branch more convenient for docker-based setup, you may use it instead.

**Comment by webdjoe** [comment]
I made some edits can you just confirm that this is still working and I will update PIP - https://github.com/webdjoe/pyvesync/tree/airpur-refactor

**Comment by formatBCE** [comment]
@webdjoe I will be able to check it in several hours. If someone gonna do it earlier - will be good :)

**Comment by formatBCE** [comment]
@webdjoe oh sorry, I totally forgot, that I don't have access to that devices anymore - person, that needed that changes, shared his device with me for verification. Now it's gone from my account, obviously.

However, if you only put that Core300S merge request, it should be fine - I included that into my version, and it works.

**Comment by webdjoe** [comment]
Sorry for the delay, latest version on pypi!

**Comment by jparchem** [comment]
@formatBCE Will you be creating a PR for the HA VeSync integration based on the code you added when you forked it?

**Comment by formatBCE** [comment]
> @formatBCE Will you be creating a PR for the HA VeSync integration based on the code you added when you forked it? 

I won't for now.
I created fork a while ago, adding Classic300s humidifier for myself. Then I tried to perform testing and stuff, but didn't even succeed in installation of test HA instance (which is required for making pull-request).
I will try to make that again at some point, but have not much time for it now.

**Comment by formatBCE** [comment]
> @formatBCE Will you be creating a PR for the HA VeSync integration based on the code you added when you forked it?

Hi! Just wanted to let you know, that i updated main branch in my repo to rely on pyvesync 1.4.1. Should work now.

**Comment by jparchem** [comment]
> Hi! Just wanted to let you know, that i updated main branch in my repo to rely on pyvesync 1.4.1. Should work now.

Thanks, @webdjoe!  Your earlier fork has been running perfectly for days.  I did submit a tiny PR [Add support for Levoit Core400S air purifier to VeSync integration](https://github.com/home-assistant/core/pull/57126) to get the Core400s working in HA.  @webdjoe if you could take a peek when you have a moment as it is only a couple lines of code and it has been tested and works great thanks to all of your hard work.  I wanted to include the Core 300s but I don't have that hardware to test with.

I'm going to continue to use your forked integration for now as I don't know how long it will take my PR to get approval. 

Thanks again to you both!

**Comment by formatBCE** [comment]
> > Hi! Just wanted to let you know, that i updated main branch in my repo to rely on pyvesync 1.4.1. Should work now.
> 
> Thanks, @webdjoe!  Your earlier fork has been running perfectly for days.  I did submit a tiny PR [Add support for Levoit Core400S air purifier to VeSync integration](https://github.com/home-assistant/core/pull/57126) to get the Core400s working in HA.  @webdjoe if you could take a peek when you have a moment as it is only a couple lines of code and it has been tested and works great thanks to all of your hard work.  I wanted to include the Core 300s but I don't have that hardware to test with.
> 
> I'm going to continue to use your forked integration for now as I don't know how long it will take my PR to get approval. 
> 
> Thanks again to you both!
> 
> 

Great job posting that!
