### ISSUE TITLE
Support for Core 300S.

### ISSUE THREAD

**Issue by hrast01** [webdjoe/pyvesync#87]
Seems like a fairly new device, probably the same as the Core200s/400s.

**Comment by hrast01** [comment]
Seems like just copying/updating the definitions for the Core200S mostly works (if not completely).  I'll see about setting up a PR for this tomorrow.

**Comment by webdjoe** [comment]
Thank you for the pull request. I combined the 300s and 200s classes. Can you please confirm that it still works? https://github.com/webdjoe/pyvesync/tree/airpur-refactor

**Comment by webdjoe** [comment]
Latest version on pypi

**Comment by icebear74** [comment]
Wont work right .. C Here https://github.com/webdjoe/pyvesync/issues/92#issuecomment-939690924
300s is more like 400s ... It has Air Detection (in %) and more than one Automatic Mode (Silent Mode for Automatic eg ..)
