### ISSUE TITLE
Please update PyPi and bump version

### ISSUE THREAD

**Issue by jparchem** [webdjoe/pyvesync#90]
@webdjoe Would it be possible to get the latest version of master into PyPi?  It is using an older version from April and missing out on some of the new functionality that has been merged in since then.  A version bump would be most welcome too!

**Comment by formatBCE** [comment]
+1 to this. Core 400S is working in this repo version, but does not work with version, installed from pip.

**Comment by webdjoe** [comment]
Coming right up, just need someone to test the 300s & 200S are working

**Comment by jparchem** [comment]
Thanks!  If it helps, I grabbed the latest and dropped it directly into a HA dev instance and can confirm that both the 200S and 400S worked perfectly.

**Comment by webdjoe** [comment]
Can you please test this branch https://github.com/webdjoe/pyvesync/tree/airpur-refactor

**Comment by jparchem** [comment]
> Can you please test this branch https://github.com/webdjoe/pyvesync/tree/airpur-refactor

@webdjoe Joe- I can confirm the latest changes in the airpur-refactor branch are working perfectly.

I  updated `/usr/local/lib/python3.9/site-packages/pyvesync` with changes from the airpur-refactor branch and updated home assistants `vesync/fan.py` as needed to include the Core400S.  I am able to see all of the attributes (including AQI on the 400S) and control all aspects of the air purifiers. 

It's ready to go from my perspective.  Thanks for your hard work!

**Comment by webdjoe** [comment]
Sorry for the delay, it's up!

**Comment by jparchem** [comment]
> Sorry for the delay, it's up!

Fantastic and thanks again.
