### ISSUE TITLE
Add HomeAssistant support for Classic300S Humidifier

### ISSUE THREAD

**Issue by kdvlr** [webdjoe/pyvesync#93]
Would it be possible to add support for this humidifier ? It looks like @provinzio started on the integration. I am not able to make it work, but they mention that it works. 

Would you be able to leverage this work and add Classic300 as a supported humidifier?

Here's the PR - https://github.com/home-assistant/core/pull/49956

**Comment by ronytomen** [comment]
https://github.com/home-assistant/core/pull/57126

**Comment by sdrapha** [comment]
> 
> 
> [home-assistant/core#57126](https://github.com/home-assistant/core/pull/57126)

Just adding some information that the Levoit Core's are not the same thing of Levoit Classic's, the Classic series are Humidifiers, and the Core Series are HEPA Filters basically.

**Comment by webdjoe** [comment]
I haven't used HA in quite a while so I'm not too up to date on the current architecture. Don't have the time currently, but maybe in the future I will give it a shot.
