### ISSUE TITLE
Q: Local API

### ISSUE THREAD

**Issue by RaresAil** [webdjoe/pyvesync#97]
Hey, do you know if it is possible to have a local API and not to use the Cloud one?

**Comment by hoaxlayer** [comment]
On a related note, where is it possible to find more documentation about Vesync's API? I took a look at the Helpers files but couldn't find a documentation source.

**Comment by webdjoe** [comment]
The devices must connect to VeSync servers to work. Haven't found it possible to run locally.

**Comment by RaresAil** [comment]
Thank you
