### ISSUE TITLE
Add Support for Dual 200S Smart Top-Fill Humidifier

### ISSUE THREAD

**Issue by bf3883** [webdjoe/pyvesync#99]
If it possible please add support for the Dual 200S.
If I can help with data, please tell me.
Sry for my bad english

**Comment by bf3883** [comment]
oh sry the dual 200s is already supported,
but when i call update only the classic300s shown in list and not the dual200s

**Comment by Godfather95** [comment]
I also have an Dual 200S but it is showing up as LUH-D301S-WEU by the API. Can you please add LUH-D301S-WEU to the List of Devicess identified as Dual 200S.

**Comment by webdjoe** [comment]
I've updated the device types. Please test to make sure it works properly before I publish package #104

**Comment by webdjoe** [comment]
released in 1.4.3
